### ISSUE TITLE
issue with filter profiles?

### ISSUE THREAD

**Issue by stellarpuffin** [mfouesneau/pyphot#12]
Hi,

Can I ask how did you define the filters in Pyphot, because I noticed that at least some of them do not match with archival values?

I made a plot of a 20,000K blackbody and then plotted the transmission curves of you Ground_Johnson_V and HST_WFPC2_F555W with the corresponding filters from the SVO Filter Profile Service, and they do not match. Most importantly the f.transmit() for the Pyphot Ground Johnson V filter shows that the filter has a bandwidth of over 3000 Angstrom and it peaks around 3000 Angstrom.

I am attaching a copy of that plot

![figure_1](https://user-images.githubusercontent.com/12701152/40640232-bebcc340-6347-11e8-9f95-32c57c015aa0.png)

**Comment by mfouesneau** [comment]
This is surprising because I checked against SVO quite recently.

if I just look at the description of the filter:

```python
>>> lib['GROUND_JOHNSON_V'].info()
Filter object information:
    name:                 GROUND_JOHNSON_V
    detector type:        energy
    wavelength units:     AA
    central wavelength:   5504.666021 angstrom
    pivot wavelength:     5492.885092 angstrom
    effective wavelength: 5438.689405 angstrom
    norm:                 870.650149
    definition contains 10000 points

    Zeropoints
        Vega: 21.099109 mag,
              3.6337607043700736e-09 erg / angstrom * centimeter ** 2 * second,
              3657.0984273591766 Jy
          AB: 21.106951 mag,
              3.607610771896633e-09 erg / angstrom * centimeter ** 2 * second,
              3630.7805477010147 Jy
          ST: 21.100000 mag,
              3.6307805477010028e-09 erg / angstrom * centimeter ** 2 * second,
              3654.0991307201225 Jy

```

And if I simply plot the filter, I obtain something similar to your red curve:
```python 
>>> f = lib['GROUND_JOHNSON_V']
>>> plt.plot(f.wavelength.to('AA').magnitude, f.transmit)
```

<img width="559" alt="screen shot 2018-05-29 at 17 38 06" src="https://user-images.githubusercontent.com/1703988/40669381-1f25d964-6367-11e8-9e7c-cf77964f2101.png">

**Comment by mfouesneau** [comment]
I guess I can close this issue then. Re-open it if needed.

**Comment by jvines** [comment]
Hi, I noticed that the transmission curve of GROUND_JOHNSON_B is incorrect... I get the following when plotting it:

![trans](https://user-images.githubusercontent.com/20781020/56411207-fc83a300-624d-11e9-868f-cb40ba0827ab.jpg)

**Comment by mfouesneau** [comment]
Can you explain why this makes you think this is incorrect?

**Comment by jvines** [comment]
The y-axis. The transmision should always be a number between 0 and 1

**Comment by mfouesneau** [comment]
Calculations are independent of the normalization of the filters.  I suppose it is a percent transmission unit.

**Comment by jvines** [comment]
But from what I saw in your code, in the case of apply_transmision you multiply the transmision curve to the flux, so having the curve go to values such as 70 would make the flux stronger, unless I skipped the part where you ignore the fact that it's values are  > 1
