### ISSUE TITLE
TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by pziphi** [mfouesneau/pyphot#13]
Hi,

I was trying to use PyPhot to do synthetic photometry for a star, for which I have the calibrated spectra.
The wavelength values are stored in the array: **lamb** and the calibrated flux values are stored in the array **spectra**.  I was following the quick start guide given in the documentation and the code gives me the error: **TypeError: only integer scalar arrays can be converted to a scalar index**

```
import numpy as np
import pyphot

lib = pyphot.get_library()
f = lib['SDSS_r']

fluxes = f.get_flux(lamb, spectra, axis=-1)
Warning: assuming units are consistent
--------------------------------------------------------------------------
TypeError                                Traceback (most recent call last)
<ipython-input-44-bc534503aad0> in <module>()
----> 1 fluxes = f.get_flux(lamb, spectra, axis=-1)

/home/user/.local/lib/python2.7/site-packages/pyphot/phot.pyc in get_flux(self, slamb, sflux, axis)
    248             Energy of the spectrum within the filter
    249         """
--> 250         return self.getFlux(slamb, sflux, axis=axis)
    251 
    252     def reinterp(self, lamb):

/home/user/.local/lib/python2.7/site-packages/pyphot/phot.pyc in getFlux(self, slamb, sflux, axis)
    214                 _sflux = sflux[:, ind]
    215             except:
--> 216                 _sflux = sflux[ind]
    217             # limit integrals to where necessary
    218             ind = ifT > 0.

TypeError: only integer scalar arrays can be converted to a scalar index
```

When searched online I saw that the issue appears to be related to the latest version of NumPy.
The version of NumPy that I am using is 1.14.5.

Can anyone suggest me a fix, please?

**Comment by mfouesneau** [comment]
I cannot reproduce the issue.

```python
import pyphot
lib = pyphot.get_library()
f = lib['SDSS_r']
from pyphot.vega import Vega
vega = Vega()
f.get_flux(vega.wavelength, vega.flux)
f.get_flux(vega.wavelength.magnitude, vega.flux.magnitude)
```

Please provide more information.
tests above done with 
```np.__version__ = '1.14.5'```

**Comment by mfouesneau** [comment]
You can use numpy arrays instead of lists and that will work with a unit warning.

The only necessary unit is on the wavelength (the code does not handle flux units yet).

A simple multiplication between your array and the unit object is enough. (very similar to astropy units)

```python
from pyphot import unit

wave_unit = wave * unit['nm']
```
