### ISSUE TITLE
SDSS filters: incorrect treatment

### ISSUE THREAD

**Issue by joannawooastro** [mfouesneau/pyphot#14]
I noticed that the SDSS filters are treated as photon counters, but according to the Filter Profile Service, they are energy counters (eg, http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=SLOAN/SDSS.g).  Therefore, the pivot wavelengths and fluxes from get_flux are incorrect by a small amount.

**Comment by mfouesneau** [comment]
As far as I know, there is no more energy detector in the optical, so that's new to me. Of course, that changes things, I'll have a look. This could be a transmission curve definition. You can change them manually when using them with `set_type` until I clarify the situation.

**Comment by mfouesneau** [comment]
As far as I can dig, I am using the correct definition of SDSS transmissions. Based on the SDSS page: http://classic.sdss.org/dr7/instruments/imager/, you can see that I get the right mean wavelength values.  As far as I can tell, I believe this is a mistake on the SVO side, but I'll double check with SDSS gurus.

**Comment by mfouesneau** [comment]
According to SDSS people I talked to, its curves are defined in counts, not energy. Closing this issue.
