### ISSUE TITLE
Incorrect transmission curve?

### ISSUE THREAD

**Issue by jvines** [mfouesneau/pyphot#17]
Hi,

I was working with pyphot and I found that when plotting the transmission curve for GROUND_JOHNSON_B I get the following:

![download](https://user-images.githubusercontent.com/20781020/56451280-fa2a5300-62f8-11e9-819c-2561dd6f5017.png)

which is obviously incorrect.

Cheers,

Jose V.

**Comment by mfouesneau** [comment]
I get the right passband

f = pyphot.get_library()['GROUND_JOHNSON_B']
plt.plot(f.wavelength, f.transmit) 

![image](https://user-images.githubusercontent.com/1703988/67935032-571c9500-fbc9-11e9-992d-1ae31bcf5bdf.png)

It seems you have the wrong x-values
