### ISSUE TITLE
Kepler and/or TESS filters?

### ISSUE THREAD

**Issue by jvines** [mfouesneau/pyphot#19]
[Enchancement and question!]
Would it be possible to add Kepler or TESS filters to the filter library? And on a slightly different note, what information do I need to add a custom filter myself and save it in the HDF file for later re-use??

**Comment by mfouesneau** [comment]
check the API for making a filter then you have functions to store them in an hdf5 library.

if you have ASCII versions and want to share, I can add them to the standard one

**Comment by jvines** [comment]
In that case, would it be possible for you to add the stromgren uvby filters? I found the response functions here: https://gcpd.physics.muni.cz/filters/fil04.html

**Comment by mfouesneau** [comment]
Can you tell me if these are energy or photon counters? the website has broken links

**Comment by jvines** [comment]
Hi,

This is the broken link:  https://gcpd.physics.muni.cz/ph04.html

I'm unsure whether it's energy or photon counters. I also found the TESS response filter (http://svo2.cab.inta-csic.es/theory/fps/index.php?id=TESS/TESS.Red&&mode=browse&gname=TESS&gname2=TESS#filter) and Kepler's (http://svo2.cab.inta-csic.es/theory/fps/index.php?id=Kepler/Kepler.K&&mode=browse&gname=Kepler&gname2=Kepler#filter)

**Comment by mfouesneau** [comment]
Merged branch.
