### ISSUE TITLE
References for response curves

### ISSUE THREAD

**Issue by karllark** [mfouesneau/pyphot#21]
The origin of the filter/response curves would be really useful from a traceability/reproduciblity standpoint (e.g, references).  Is this information available somewhere?  I looked in the docs, but did not find it easily.

**Comment by mfouesneau** [comment]
Agreed, but references have been lost in 15 years... Recent ones have them in their ascii header

**Comment by karllark** [comment]
That is a bummer.

**Comment by mfouesneau** [comment]
I also added the SVO service, which could deal with the source referencing if the passbands are provided.
