### ISSUE TITLE
My own set of filters

### ISSUE THREAD

**Issue by gserrano990** [mfouesneau/pyphot#22]
Hi,

How can I include my own set of filters in the pyphot library? I have the transmission profiles. These are for CCD detectors.

Thanks

**Comment by mfouesneau** [comment]
Are you looking for the following section in the documentation?
http://mfouesneau.github.io/docs/pyphot/more_examples.html#defining-your-own-passband

or to register a new filter in the library file or creating a new library?

**Comment by gserrano990** [comment]
Hi,

I'd like to create a new library with new filters using their transmission curves.

**Comment by gserrano990** [comment]
Or add the new filters to the existing library.

**Comment by mfouesneau** [comment]
You can make csv files and load them with the Ascii Library class

If you are worried about formatting them properly, you can make pyphot do it for you.

For every filter you want to have, you make a UnitFilter object (linked to the documentation above)
and make a library object, and `add_filter` or `add_filters`. It will generate the files for you.

If you prefer an hdf5 file at the end (a single file is good to have), there is a `to_hdf` method.

Let me know if this give you all the info.

**Comment by mfouesneau** [comment]
I suppose the solution above worked. Re-open the issue if not.
