### ISSUE TITLE
References of the Lick indices

### ISSUE THREAD

**Issue by ViniciusBranco** [mfouesneau/pyphot#27]
I have been trying to relate the calculated lick indices to their references but I am not finding it directly anywhere.  Specifically, what is the 'LB13' reference for the indexes "Ca1_LB13", "Ca2_LB13" and "Ca3_LB13"? Maybe adding a "Ref" column to the band table could specify the references to each index.

**Comment by mfouesneau** [comment]
La Barbera F., Ferreras I., Vazdekis A., de la Rosa I. G., de Carvalho R. R., Trevisan M., Falcon-Barroso J., Ricciardelli E., 2013, MNRAS, 433, 3017 (LB13)

most of the libraries are compilations over many years from many persons. Sadly, I know references should be added, but takes a lot of time.

**Comment by ViniciusBranco** [comment]
Hi, Morgan!

I understand the issue, it is complicated indeed. But thank you for the
information and rapid response!

Cheers,

*Vinicius Branco*
PhD. Candidate
*Instituto de Astronomia, Geofísica e Ciências Atmosféricas (IAG)*
*Universidade de São Paulo (USP)*
***@***.***
+55 (11) 98509-4208


Em ter., 23 de mar. de 2021 às 05:05, Morgan Fouesneau <
***@***.***> escreveu:

**Comment by mfouesneau** [comment]
Closing.
