### ISSUE TITLE
Make code pip installable?

### ISSUE THREAD

**Issue by klukosiute** [mfouesneau/pyphot#28]
Hi, I'm really enjoying using your code, it makes my life a lot easier. It would be great for users if it was packaged and uploaded to PyPI, so that it can be automatically installed just via `pip install pyphot` and also so that it can be listed in a requirements file and installed automatically. 

The repository looks well-organized and like it's basically ready to go and wouldn't require that much work to make this happen. Would you mind if I tried going ahead and packaging and uploading to test.pypi.org to see if it would work? If it works, then you can upload to the real index?

**Comment by mfouesneau** [comment]
go ahead. let me know if I can help.

**Comment by klukosiute** [comment]
Hey, thanks for accepting my pull request. It's up now: https://pypi.org/project/pyphot/1.1/ so `pip install pyphot` works. If you'd like to be added as a maintainer on pypi, please give me your username for that site.

**Comment by mfouesneau** [comment]
`mfouesneau`

Thanks!

**Comment by mfouesneau** [comment]
Can you give me access to the pypi project? new version needs to be made available. This will also make it through the releases automatically.

**Comment by klukosiute** [comment]
Oops sorry, thought I had already done this. You should now have the invitation.

**Comment by mfouesneau** [comment]
Thanks. Pypi is now getting automated updates from the release tags. (I also added the badge on the readme)
