### ISSUE TITLE
With regard adding new filters

### ISSUE THREAD

**Issue by jvines** [mfouesneau/pyphot#33]
Hi,

I recently added some filters to pyphot, but when calling the info method it shows an AttributeError, stating that it needs wavelength units. I fear I may have missed something while adding the filters. How could I go around to fix this?

Thanks in advance.

**Comment by mfouesneau** [comment]
Depending on using HDF5 file or ascii the method is slightly different. Ascii you need to update the header file, hdf5 you need to update the attributes of the table.

If they are loaded in memory, you can also manually set the unit attribute and this should work.

**Comment by jvines** [comment]
I used the HDF5 method. How can I update the attributes??

**Comment by mfouesneau** [comment]
Did you create the `SM_g` filter? it breaks the tests

**Comment by mfouesneau** [comment]
Yes, so the library is broken. 
I would also not call the filters SM_... SkyMapper or Skymapper is more explicit.

Would you mind to redo it?

**Comment by jvines** [comment]
No problem. How can I address the attribute issue??

**Comment by mfouesneau** [comment]
revert the file to its previous version and redo your script.

**Comment by jvines** [comment]
No, I meant specifically the AttributeError I was getting. How can I tell pyphot the units are angstrom, for example

**Comment by mfouesneau** [comment]
When you create the filter object you have keywords to set the units properly.

**Comment by jvines** [comment]
So I can't just add them to the HDF5 file right away, then?

**Comment by jvines** [comment]
I ask mainly because the add_filter method from the pyphot.phot.Library class is not implemented and I don't remember how I added the NGTS filter succesfully

**Comment by jvines** [comment]
Just FYI, I added the filters correctly this time, with a pending PR!

**Comment by mfouesneau** [comment]
Unit tests are now created to avoid merging when the file is broken.
