### ISSUE TITLE
Have extractPhotometry and extractSEDs return photometry as quantities

### ISSUE THREAD

**Issue by sundarjhu** [mfouesneau/pyphot#40]
While the `get_flux` method applied on a single filter returns the corresponding flux as a quantity, the `extractPhotometry` and `extractSEDs` methods do not. Would it be possible to have them do so? Or (if that's inefficient) to return the units of the flux in some way? Thanks!

@pscicluna

**Comment by mfouesneau** [comment]
These two should be deprecated. I do not recommend these functions that are only valid for specific (counter) filters. These are unsafe to use.

**Comment by mfouesneau** [comment]
You should use the filter methods directly instead. There is a small overhead of checking units but worth it for the robustness.

**Comment by mfouesneau** [comment]
#41 deprecating functions.
