### ISSUE TITLE
ezunits equivalency for the Kelvin

### ISSUE THREAD

**Issue by sundarjhu** [mfouesneau/pyphot#43]
The ezunits package defines the following equivalency (line 42 of default_en.txt):
degK = [temperature] = K = kelvin
degK is invalid for the absolute temperature scale and this usage should be discouraged.

**Comment by sundarjhu** [comment]
The Rankine scale is also an absolute one.

**Comment by mfouesneau** [comment]
I do not understand your comment. Kelvin is a valid temperature unit and is very common in astrophysics.

**Comment by sundarjhu** [comment]
Apologies, I wasn't clear. Since the Kelvin is a unit of an absolute temperature scale, it should not be referred to as "degrees Kelvin". My comment was specifically about the "deg" in the "degK".

Also, I've been corrected about the Rankine scale. Although it is an absolute scale, apparently degrees Rankine is acceptable, so I withdraw my comment about it.

**Comment by mfouesneau** [comment]
This comment should then be done for a different package: [pint](https://github.com/hgrecco/pint)
