### ISSUE TITLE
Where can I find the doucumentation (tutorial) for pyphot?

### ISSUE THREAD

**Issue by mookeonjung** [mfouesneau/pyphot#44]
Thank you for your very convenient package.
But I cannot find the tutorial documentation for pyphot since sometime and I think that the previous one (http://mfouesneau.github.io/docs/pyphot/) is not working anymore.
Is there another way to get the tutorial documentation?

**Comment by mfouesneau** [comment]
https://mfouesneau.github.io/pyphot/ 
Thanks for pointing that the url was incorrect.

**Comment by mookeonjung** [comment]
I found the url in the 'pyphot/examples/Sun_Vega.ipynb' file.
The first and most results of searching 'pyphot' in Google also give the same past url.
Thank your for your response!

**Comment by mfouesneau** [comment]
The documentation should be updated. Let me know if not.
