### ISSUE TITLE
ImportError: cannot import name 'Iterable' from 'collections'

### ISSUE THREAD

**Issue by zzxihep** [mfouesneau/pyphot#47]
I installed pyphot using pip, and when I import pyphot, there is a ImportError
```python
ImportError: cannot import name 'Iterable' from 'collections'
```
It seems like the code in the pint.py line:28 should adjust to
```python
from collections.abc import Iterable
```

**Comment by mfouesneau** [comment]
596f43f should add python 3.10 tests now

**Comment by mfouesneau** [comment]
pull request #48 to fix this.
