### ISSUE TITLE
【Question】How to calculate Luminosity (unit :erg/s) from a given apparent magnitude of a filter?

### ISSUE THREAD

**Issue by bszzhzxyf** [mfouesneau/pyphot#52]
Hello，Can I ask a simple question here
If I have a source with a magnitude within a given filter(such as SDSS g band),  I can get the zeropoint of this filter using "pyphot"，and convert magnitude to Flux (F_lambda)，with a unit erg/cm^2/A/s 。 Then I can calculate Luminosity by using this formula  L_lambda = 4*pi*D^2*F_lambda， the unit of Luminosity is erg /A /s now.  But how can I turn it to erg/s ?   By multiply the integration of filter transmission curve ？   Different photometric systems have different different defination of flux density , and I'm confused

**Comment by mfouesneau** [comment]
The total luminosity of a star will be the L_λ you calculated with a correction that you do not see the entire spectrum. This correction is the bolometric correction that depends on the star type and the passband.
Some stellar atmosphere models provide bolometric corrections, but that's beyond pyphot

**Comment by bszzhzxyf** [comment]
Thanks :） .  By the way, I also find a typo in the document , “Details on predicting photometry“ (https://mfouesneau.github.io/pyphot/photometry.html#details-on-predicting-photometry)，The definition of Jansky should be 10^−23erg/s/cm2/Hz  
 .

**Comment by mfouesneau** [comment]
Thanks for the typo. It is corrected.
