### ISSUE TITLE
f.get_flux(lamb, spectra)

### ISSUE THREAD

**Issue by isteniomorais** [mfouesneau/pyphot#54]
Good afternoon!
I have some doubts about the f.get_flux command. Does this command perform a filter interpolation on the object's spectrum data, or just calculate the integrated flux through the filter f?

And another doubt. I would like to include Saburu's filters, Hyper Suprime-Cam: Filters, in Pyphot's filter library. Is there a way to do this without using the line "tophat = Filter(wave, transmit, name='tophat', dtype='photon', unit='Angstrom')"?

**Comment by mfouesneau** [comment]
To allow integration, the spectra and the passband must be defined using the same wavelength values. If you look at the code, you will see that the passband is interpolated onto the spectrum definition.

You can add any filter you want using the example you mentioned. How else would you include it to also handle proper units?

**Comment by mfouesneau** [comment]
You do not have to deal with the spectra range manually. Pyphot does the mathematical integral here as defined in the documentation.

pyphot.astropy.sandbox.UnitAscii_Library(source)[[source]](https://mfouesneau.github.io/pyphot/_modules/pyphot/astropy/sandbox.html#UnitAscii_Library)
is probably what you want to look at to create your library.

**Comment by isteniomorais** [comment]
mfousneau
Does Pyphot work with redshift? If I want to correct the redshift of a model's data, could I do it directly in Pyphot?

**Comment by mfouesneau** [comment]
Please look at the scope of the code. Redshift is handled on the user side.
