### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by stellarpuffin** [mfouesneau/pyphot#9]
Hi,
I just installed the package with pip and once I tried to import it I get the following error. Any idea how to fix this?

`In [2]: import pyphot
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-287e8f22193a> in <module>()
----> 1 import pyphot

/usr/local/lib/python2.7/site-packages/pyphot/__init__.py in <module>()
----> 1 from .phot import (Library, Ascii_Library, HDF_Library, Filter, get_library)
      2 from .licks import (LickLibrary, LickIndex, reduce_resolution)
      3 from .ezunits import unit
      4 from .helpers import (STmag_from_flux, STmag_to_flux, extractPhotometry,
      5                       extractSEDs, fluxErrTomag, fluxToMag, magErrToFlux,

/usr/local/lib/python2.7/site-packages/pyphot/phot.py in <module>()
     17 from __future__ import print_function, division
     18 import numpy as np
---> 19 import tables
     20 from scipy.integrate import trapz
     21 

ImportError: No module named tables`

**Comment by mfouesneau** [comment]
you are missing pytables (tables) hdf5 package.

I did not handle the requirements sorry.
